In [2]:
import numpy as np

docs = np.array([[0.3, -1.2, 0.5, 0.9],
               [0.7, 2.2, 0.3, 0.1],
               [1.92, -1.2, -0.7, 1.9],
               [0.32, 1.7, -0.5, -1.9],
               [4.3, 3.8, -0.1, 0.88]])

query = np.array([0.4, 1.8, -2.3, 0.1])

query_len = np.linalg.norm(query)
query_len

np.float64(2.949576240750525)

In [3]:
q_norm = query / query_len
q_norm

array([ 0.1356127 ,  0.61025715, -0.77977303,  0.03390318])

In [5]:
qq = np.linalg.norm(q_norm)
qq

np.float64(1.0)

In [8]:
docs_len = np.linalg.norm(docs, axis=1, keepdims=True)
docs_len

array([[1.60934769],
       [2.33023604],
       [3.03749897],
       [2.61770892],
       [5.80641025]])

In [9]:
docs_norm = docs / docs_len
docs_norm

array([[ 0.18641093, -0.74564372,  0.31068488,  0.55923279],
       [ 0.30039875,  0.94411037,  0.12874232,  0.04291411],
       [ 0.63209898, -0.39506186, -0.23045275,  0.62551462],
       [ 0.1222443 ,  0.64942285, -0.19100672, -0.72582554],
       [ 0.74056083,  0.65444911, -0.01722234,  0.15155664]])

In [10]:
similarities = docs_norm @ q_norm
similarities

array([-0.65305865,  0.51795312,  0.0455391 ,  0.53722692,  0.51837947])

In [11]:
best_index_doc = np.argmax(similarities)
best_index_doc

np.int64(3)